apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-deployment
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:   # spec.selector is required!
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master   # spec.template.metadata.labels must have a valid jmeter_mode.
        app: jmeter-server
    spec:
      containers:
        - name: jmeter
          image: justb4/jmeter
          args:
            - "-n"
            - "-t"
            - "/etc/jmeter/jmeter_run.jmx"
          volumeMounts:
            - name: jmeter-config-volume
              mountPath: /etc/jmeter
      volumes:
        - name: jmeter-config-volume
          configMap:
            defaultMode: 420
            name: jmeter-config
